zend_extension=xdebug.so
serverName=wp-cypress
xdebug.client_host=host.docker.internal
xdebug.mode=debug,trace
xdebug.idekey=PhpStorm
; settings for trace
xdebug.collect_params=true
xdebug.collect_return=false
xdebug.output_dir=/tmp
xdebug.start_with_request=trigger
xdebug.trace_output_name=trace.%t
xdebug.trigger_value=""
xdebug.trace_format=0
xdebug.var_display_max_children=7
xdebug.var_display_max_data=256
xdebug.var_display_max_depth=3
